// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqx7ixqIQ-kwE6HEcZAyilLWSSkma293o',
    appId: '1:198367418692:web:58c379a7a8b7a1a248df11',
    messagingSenderId: '198367418692',
    projectId: 'e-commere-35ccb',
    authDomain: 'e-commere-35ccb.firebaseapp.com',
    storageBucket: 'e-commere-35ccb.appspot.com',
    measurementId: 'G-1XE8B4CK1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwo--xYhtFohvNgkNKVvCEYmTEW6cRUQM',
    appId: '1:198367418692:android:382011820a58b19f48df11',
    messagingSenderId: '198367418692',
    projectId: 'e-commere-35ccb',
    storageBucket: 'e-commere-35ccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0sNj1CszrM7MFvEm6OM-BiyZS-oxVR4',
    appId: '1:198367418692:ios:d1a14c4fcdd0007a48df11',
    messagingSenderId: '198367418692',
    projectId: 'e-commere-35ccb',
    storageBucket: 'e-commere-35ccb.appspot.com',
    iosClientId:
        '198367418692-f0e2kskccp49m84aaebkib8rul8mtg3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0sNj1CszrM7MFvEm6OM-BiyZS-oxVR4',
    appId: '1:198367418692:ios:1e0cf7e5c891d5d148df11',
    messagingSenderId: '198367418692',
    projectId: 'e-commere-35ccb',
    storageBucket: 'e-commere-35ccb.appspot.com',
    iosClientId:
        '198367418692-iforpamjblv5rr566odoj1b3ntf6crpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAudio.RunnerTests',
  );
}
